//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVCore {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /_iconList 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SVCore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap page {
            get {
                object obj = ResourceManager.GetObject("page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 删除图元 的本地化字符串。
        /// </summary>
        internal static string 删除图元 {
            get {
                return ResourceManager.GetString("删除图元", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类列表为空，才能执行删除 的本地化字符串。
        /// </summary>
        internal static string 删除图元分类 {
            get {
                return ResourceManager.GetString("删除图元分类", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建分类 的本地化字符串。
        /// </summary>
        internal static string 新建分类 {
            get {
                return ResourceManager.GetString("新建分类", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名称不能为空! 的本地化字符串。
        /// </summary>
        internal static string 模板名称不能为空 {
            get {
                return ResourceManager.GetString("模板名称不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板已经存在 的本地化字符串。
        /// </summary>
        internal static string 模板已经存在 {
            get {
                return ResourceManager.GetString("模板已经存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加图元 的本地化字符串。
        /// </summary>
        internal static string 添加图元 {
            get {
                return ResourceManager.GetString("添加图元", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string 确定 {
            get {
                return ResourceManager.GetString("确定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除分类 的本地化字符串。
        /// </summary>
        internal static string 移除分类 {
            get {
                return ResourceManager.GetString("移除分类", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        internal static string 重命名 {
            get {
                return ResourceManager.GetString("重命名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要选择模板 的本地化字符串。
        /// </summary>
        internal static string 需要选择模板 {
            get {
                return ResourceManager.GetString("需要选择模板", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面名称为空 的本地化字符串。
        /// </summary>
        internal static string 页面名称为空 {
            get {
                return ResourceManager.GetString("页面名称为空", resourceCulture);
            }
        }
    }
}
